env: "development"
port: "50052"

database:
  url: "postgres://profile_user:Bogdan_20@localhost:5432/user_profile_db?sslmode=disable"

redis:
  url: "redis://localhost:6379/1"

cache:
  url: "1h"

logging:
  level: "debug"